### ISSUE TITLE
Unable to preview courses with certain components

### ISSUE THREAD

**Issue by canstudios-scottd** [adapt-security/adapt-authoring-ui#110]
Currently there are many components which cause and error or a blank white page when attempting to preview a course. It may be that these components are still undergoing some development.

Some of the components are Accordion, Graphic, Narrative, Text Input.

It may be that any components which have items are the root cause.

**Comment by taylortom** [comment]
Latest broken component list:
- Narrative (page doesn't render)
- Text input (input itself doesn't render, rest of the component is fine)

**Comment by taylortom** [comment]
```
Uncaught (in promise) TypeError: Cannot read property '_narrative' of undefined
    at NarrativeView.evaluateNavigation (adapt.min.js:1)
    at NarrativeView.setStage (adapt.min.js:1)
    at NarrativeView.onItemsActiveChange (adapt.min.js:1)
    at p (backbone.min.js:2)
    at v (backbone.min.js:2)
    at u (backbone.min.js:2)
    at e.Collection.a.trigger (backbone.min.js:2)
    at e.Collection._onModelEvent (backbone.min.js:2)
    at p (backbone.min.js:2)
    at v (backbone.min.js:2)
```

**Comment by taylortom** [comment]
Fixed

**Comment by scottdarcydigital** [comment]
It seems as though accordion is not able to have any items added to it in the AT (this shows an error when clicking 'add'). This may be related to another issue, but as a result this one cannot be closed.

**Comment by joe-allen-89** [comment]
Was just checking this as a few of the errors were fixed by a component upgrade (known issue with comps fixed with previous releases). 

The above error mentioned with the accordion is a strange one, if I add a new accordion I can add items normally, if I import a course with an accordion and try to add an item I get the error 'Item schema~vanilla-component could not be found'. I expected to see the same issue on other item comps but only seems to be effecting the accordion.

**Comment by chris-steele** [comment]
I've just tried to replicate the most recent problem report by @joe-allen-89 - I could not replicate the issue with accordion.
