### ISSUE TITLE
After selecting Add [tag]... and saving, the tag is not saved

### ISSUE THREAD

**Issue by chris-steele** [adapt-security/adapt-authoring-ui#247]
### What happened?

I typed a new tag name to add to my course, clicked _Add [tag]..._ and then saved my changes. When I returned to the course settings the tag was not present. Note: the tag name had actually been stored in the database and I was subsequently able to select it from the drop down list, save and see it successfully added to the course.

### Expected behaviour

After creating a new tag and choosing save the tag should be added without requiring me to select it from the drop down list and save a second time.

### Authoring tool version

master

**Comment by joe-allen-89** [comment]
Tested this with the latest version while adding tags to a project, when I type a tag, press enter it shows in the bar as expected, when the new tag is removed it's then visible in the drop down, on clicking save then returning to the course the selected tags all appear as expected. 

This issue seems to have been resolved with the previous set of tag updates.
