### ISSUE TITLE
Intermitent issue of components not showing in the sidebar

### ISSUE THREAD

**Issue by joe-allen-89** [adapt-security/adapt-authoring-ui#274]
### What happened?

Clicked 'add component', sidebar appears but is blank, close and reopen and all components are then shown. This is a very intermitent issue which has no console errors shown and I'm unable to replicate on a regular basis.

### Expected behaviour

All components should be shown ever time. 

### Steps to reproduce

I'm unable to replicate on a regular basis, but click 'add component' and occasionally the sidebar appears empty.

**Comment by taylortom** [comment]
Further reports from two Kineo testers:

- "I've noticed that when I'm trying to add a component to a block, the list is blank and I have to refresh the page in order to load the component list."
- "I've managed to replicate once (whilst using Firefox). I entered an existing course, added a new block, added a component and the component list had the title (Add a component/Select a component) and the search box but was otherwise empty. Closing the drawer and immediately clicking the 'Add component' button resolved the issue for me."
